dependencies:
  - absl-py=0.8.0
  - alpaca-trade-api
  - asn1crypto=0.24.0
  - astor=0.8.0
  - attrs=19.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.0
  - bleach=3.1.0
  - blinker=1.4
  - blis=0.4.1
  - catalogue=0.0.8
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - colorama=0.4.1
  - cryptography=2.8
  - cycler=0.10.0
  - cymem=2.0.2
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - future=0.17.1
  - gast=0.2.2
  - google-pasta=0.1.8
  - h5py=2.10.0
  - idna=2.8
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - Jinja2=2.10.1
  - joblib=0.13.2
  - jsonschema=3.0.2
  - jupyter
  - Keras-Applications=1.0.8
  - Keras-Preprocessing=1.1.0
  - kiwisolver=1.1.0
  - lxml=4.4.1
  - Markdown=3.1.1
  - MarkupSafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - murmurhash=1.0.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - nltk=3.4.5
  - notebook=6.0.1
  - numpy=1.17.2
  - oauthlib=3.1.0
  - pandas=0.25.1
  - pandas-datareader=0.8.1
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - plac=0.9.6
  - plotly=4.3.0
  - preshed=3.0.2
  - protobuf=3.9.2
  - ptyprocess=0.6.0
  - pycparser=2.19
  - Pygments=2.4.2
  - PyJWT=1.7.1
  - pyOpenSSL=19.0.0
  - pyparsing=2.4.2
  - PyPDF2=1.26.0
  - pyrsistent=0.15.4
  - PySocks=1.7.0
  - python-dateutil=2.8.0
  - python-twitter=3.5
  - pytz=2019.2
  - pywinpty=0.5.5
  - pyzmq=18.1.0
  - qtconsole=4.5.5
  - requests=2.22.0
  - requests-oauthlib=1.2.0
  - retrying=1.3.3
  - rope=0.14.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - Send2Trash=1.5.0
  - six=1.12.0
  - soupsieve=1.9.3
  - spacy=2.2.3
  - srsly=0.1.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - thinc
  - tornado=6.0.3
  - tqdm=4.35.0
  - traitlets=4.3.2
  - urllib3=1.24.3
  - wasabi=0.4.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websocket-client=0.56.0
  - websockets=8.0.2
  - Werkzeug=0.16.0
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - zipp=0.6.0
